name: CI/CD Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Robot Checkout lấy mã nguồn
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      # Bước 2: Cài đặt Java để build file .jar
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Bước 3: Build Maven (Trỏ đúng vào thư mục chứa pom.xml)
      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./Ho_Nguyen_Dang_Khoi_DOCKER

      # Bước 4: Robot Docker Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v4.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bước 5: Robot Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v7.0.0
        with:
          context: . 
          file: ./Ho_Nguyen_Dang_Khoi_DOCKER/Dockerfile 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/java-springboot-app:latest
